services:
  jrebel-app:
    image: registry.cn-hangzhou.aliyuncs.com/afrank/jrebel-license-serveer:latest
    container_name: jrebel-license-server
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - SERVER_PREFIX=https://jrebel.afrank.cn
    volumes:
      - ./data:/app/data

